name: 'big_data'
version: '1.0.0'
config-version: 2

profile: 'big_data'

model-paths: ["models"]
seed-paths: ["crm_source", "erp_source"]
test-paths: ["tests"]
macro-paths: ["macros"]
analysis-paths: ["analyses"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

seeds:
  big_data:
    +schema: bronze
    +quote_columns: false
    crm_clients:
      +column_types:
        telephone: varchar(20)

models:
  big_data:
    silver:
      +schema: silver
      +materialized: table
    gold:
      +schema: gold
      +materialized: table
